logging:
  level:
    ROOT: info

broker.host: ${ACTIVE_MQ_URL:localhost}

spring:
  application.name: action-monitor-service
  activemq:
    user: admin
    password: admin
    broker-url: ${ACTIVE_MQ_URL:localhost}:61616
    in-memory: false
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    show-sql: false
    hibernate.naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
    database-platform: org.hibernate.dialect.H2Dialect

flyway:
  validate-on-migrate: true
  enabled: true
  user: sa
  password:

application.version: 0.0.1